# FIRST

In [1]:
import numpy as np

# Basics

In [13]:
a = np.array([2,5,7], dtype='int16')
print(a)

[2 5 7]


In [14]:
b = np.array([[8.34, 5.89, 2.12], [93.5, 43.1, 23.9]])
print(b)

[[ 8.34  5.89  2.12]
 [93.5  43.1  23.9 ]]


# Get dimension

In [15]:
a.ndim

1

In [16]:
b.ndim

2

# Get shape

In [17]:
a.shape

(3,)

In [18]:
b.shape

(2, 3)

# Get type

In [19]:
a.dtype

dtype('int16')

In [20]:
b.dtype

dtype('float64')

# Get size

In [22]:
a.itemsize # 2 bytes = 16 bits

2

In [25]:
b.itemsize

8

# Get total size

In [23]:
a.size * a.itemsize

6

In [24]:
a.nbytes

6

In [26]:
b.size * b.itemsize

48

In [27]:
b.nbytes

48

# SECOND : Accessing and changing specific elements,rows, columns

In [4]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
a.shape

(2, 7)

In [7]:
a[1,5]

13

In [8]:
a[1,-2]

13

In [9]:
#specifc row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [10]:
#specific column
a[:, 3]

array([ 4, 11])

In [15]:
#[startingindex : endingindex : stepsize]
a[1, 1:6:2]

array([ 9, 11, 13])

In [17]:
a[1, 1:-1:2]

array([ 9, 11, 13])

In [18]:
a[1,5] = 34
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 34 14]]


In [20]:
a[:,3] = 0
print(a)

[[ 1  2  3  0  5  6  7]
 [ 8  9 10  0 12 34 14]]


In [23]:
a[1,1:-1:2] = [100,101,102]
print(a)

[[  1   2   3   0   5   6   7]
 [  8 100  10 101  12 102  14]]


## 3d array

In [26]:
c=np.array([[[6,7], [1,2]],[[8,9],[3,4]]])
print(c)

[[[6 7]
  [1 2]]

 [[8 9]
  [3 4]]]


In [27]:
c[1][0][1]

9

# Third : Initializing different arrays

In [28]:
np.zeros(3)

array([0., 0., 0.])

In [34]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
np.zeros((2,3,4,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [36]:
np.ones((3,2,4), dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [37]:
np.full((2,2), 100)

array([[100, 100],
       [100, 100]])

In [38]:
np.full_like(a,55)

array([[55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55]])

In [39]:
np.full(a.shape,55)

array([[55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55]])

In [40]:
np.random.rand(4,2)

array([[0.92840409, 0.57178476],
       [0.80400771, 0.03865907],
       [0.84719094, 0.58529432],
       [0.06717994, 0.57555714]])

In [47]:
np.random.randint(-10,10, size=(3,4))

array([[ 7, -7, -5, -8],
       [-6, -7,  1,  2],
       [-1,  5,  9, -5]])

In [49]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
arr = np.array([1,2,3])
r3=np.repeat(arr,3)
print(r3)

[1 1 1 2 2 2 3 3 3]


In [53]:
arr2 = np.array([[1,2,3]])
r4=np.repeat(arr2,4, axis=0)
print(r4)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


# FOURTH : Problem

In [59]:
output = np.ones((5,5), dtype='int8')
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [60]:
z=np.zeros((3,3), dtype='int8')
z[1,1] = 9
print(z)

[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [61]:
output[1:-1, 1:-1] =z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# FIFTH : Copying array

In [63]:
a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20

In [64]:
print(b)

[ 1  2 20  4  5]


In [65]:
print(a)

[ 1  2 20  4  5]


In [66]:
a = np.array([1, 2, 3, 4, 5])
b = a.copy()
b[2] = 20

In [67]:
print(b)

[ 1  2 20  4  5]


In [68]:
print(a)

[1 2 3 4 5]


# SIXTH : Mathmatics

In [69]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [70]:
a+3

array([4, 5, 6, 7])

In [71]:
a-2

array([-1,  0,  1,  2])

In [72]:
a*5

array([ 5, 10, 15, 20])

In [73]:
a/5

array([0.2, 0.4, 0.6, 0.8])

In [75]:
a**2

array([ 1,  4,  9, 16])

In [74]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [76]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [79]:
a=np.ones((3,2))

b=np.full((2,3), 5)

np.matmul(a,b)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [80]:
# find deteminent
a=np.identity(3)

np.linalg.det(a)

1.0

In [82]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [84]:
np.min(stats)

1

In [98]:
np.max(stats)

6

In [86]:
np.min(stats, axis=1)

array([1, 4])

In [90]:
np.max(stats, axis=1)

array([3, 6])

In [91]:
np.max(stats, axis=0)

array([4, 5, 6])

In [92]:
np.sum(stats)

21

In [93]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [97]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1)

print(b)

[ 5 10]


# SEVENTH : Reorganising arrays

In [99]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [100]:
after=before.reshape(2,2,2)
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [101]:
after2=before.reshape(8,1)
after2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [104]:
# vertical stack

v1=np.array([0,0,0,0])
v2=np.array([2,2,2,2])

v3 = np.vstack([v1,v2,v2,v2])
print(v3)

[[0 0 0 0]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [109]:
# horizontal stack


v1=np.zeros((2,3))
v2=np.ones((2,4))

v3 = np.hstack([v1,v2,v2])
print(v3)

[[0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]]


# EIGHTH : Loading data

In [4]:
np.genfromtxt('data.txt', delimiter=',')

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [8]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [9]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [10]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [18]:
a=np.array([0,1,2,3,4,5,6,7,8,9])

In [19]:
a[[1,4,7]]

array([1, 4, 7])

In [20]:
np.any(filedata>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [21]:
np.all(filedata>50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [22]:
np.all(filedata>50, axis=1)

array([False, False, False])

In [23]:
((filedata>50) & (filedata>100))

array([[False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [26]:
(~((filedata>50) & (filedata>100)))

array([[ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [27]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])

In [31]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [28]:
a[2:4:1, :2:1]

array([[11, 12],
       [16, 17]])

In [29]:
a[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [30]:
a[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [32]:
a[[0,0,4,4,5,5],[3,4,3,4,3,4]]

array([ 4,  5, 24, 25, 29, 30])

In [33]:
a[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])